FARequest/Controllers/CharityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FARequest.Models;
using System.Data;
using System.Data.SqlClient;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using System.IO;
using FARequest.BLL;
using FARequest.DAL;


namespace FARequest.Controllers
{
    public class CharityController : Controller
    {
        private string _userId;
        private string _userRole;
        
        // GET: Requests
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            _userId = userId;

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();
            _userRole = roles[0].Value.ToString();


            DBHelper dbh = new DBHelper();
            ModelState.Clear();

            var model = new List<CharityRequestModel>();
            model = model = dbh.GetRequests(_userId, _userRole);
          
            return View(model);
            //return View(dbh.GetRequests(_userId, _userRole));
        }

        [Authorize(Roles = "Admin, Employee")]
        // GET: charity/Edit/5
        public ActionResult Edit(int id)
        {
            DBHelper dbh = new DBHelper();

            var userId = User.Identity.GetUserId();
            _userId = userId;

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();
            _userRole = roles[0].Value.ToString();

            var model = new CharityRequestModel();

            if (User.IsInRole("Admin"))
            {
                model = dbh.GetRequests(_userId, _userRole).Find(RequestModel => RequestModel.RequestId == id);
                return View("AdminEdit", model);
            }
            else
            {
                model = dbh.GetRequests(_userId, _userRole).Find(RequestModel => RequestModel.RequestId == id);
                return View("Edit", model);
            }
        }

        // POST: charity/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CharityRequestModel Requestmodel)
        {
            DBHelper dbh = new DBHelper();

            if (User.IsInRole("Admin"))
            {
                try
                {
                    dbh.UpdateRequestStatus(Requestmodel);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    string exception = "Admin Update Error" + " " + ex.ToString();
                    return View();
                }
            }
            else
            {
                try
                {
                    dbh.UpdateDetails(Requestmodel);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    string exception = "Employee Update Error" + " " + ex.ToString();
                    return View();
                }
            }
        }


        [Authorize(Roles = "Admin, Employee")]
        // GET: charity/Create
        public ActionResult CreateDocuments()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Employee")]
        // POST: charity/Create
        [HttpPost]
        public ActionResult CreateDocuments(CharityRequestModel Requestmodel, List<HttpPostedFileBase> postedFiles)
        {
            BLL.BusinessLogicLayer bll = new BusinessLogicLayer();

            var userId = User.Identity.GetUserId();
            _userId = userId;

            Requestmodel.EmployeeId = _userId;
            Requestmodel.DateSubmitted = DateTime.UtcNow;
            Requestmodel.DateModified = DateTime.UtcNow;
            Requestmodel.StatusDesc = "New";
            Requestmodel.StatusId = 1;

            bool SaveFileSuccess = false;

            if (postedFiles.Count > 1)
            {
                List<HttpPostedFileBase> allValidFiles = bll.ValidateFiles(postedFiles);
                ViewData["ApprovedFileList"] = allValidFiles;

                bool ValidTotalSize = CheckFilesTotalSize(allValidFiles);

                if (ValidTotalSize)
                {
                    SaveFileSuccess = UploadValidFiles(allValidFiles, Requestmodel);
                }

                if (SaveFileSuccess)
                {
                    SaveData(Requestmodel);
                }
            }
            else
            {
                SaveData(Requestmodel);
            }

            return View();
        }

        [Authorize(Roles = "Admin, Employee")]
        public bool SaveData(CharityRequestModel Requestmodel)
        {
            DBHelper dbh = new DBHelper();

            if (dbh.AddRequest(Requestmodel))
            {
                ViewBag.Message = "Request Details Added Successfully";
                ModelState.Clear();
                return true;
            }
            else
            {
                ViewBag.Message = "Request Details Failed";
                return false;
            }
        }

        public bool CheckFilesTotalSize(List<HttpPostedFileBase> allValidFiles)
        {
            int sumOfLength = 0;

            for (int i = 0; i < allValidFiles.Count; i++)
            {
                sumOfLength += allValidFiles[i].ContentLength;
            }

            if (sumOfLength > 15000000)
            {
                ViewData["FileSizeError"] = sumOfLength + "This cannot exceed 15MB.";
                return false;
            }
            return true;
        }

        public bool UploadValidFiles(List<HttpPostedFileBase> allValidFiles, CharityRequestModel RequestModel)
        {
            try
            {
                foreach (HttpPostedFileBase file in allValidFiles)
                {
                    if (ModelState.IsValid)
                    {
                        string path = Server.MapPath("~/Uploads/" + _userId + "/" + RequestModel.Charity + "/");
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }

                        RequestModel.DocPath = path;

                        var InputFileName = Path.GetFileName(file.FileName);
                        var ServerSavePath = Path.Combine(path + InputFileName);

                        file.SaveAs(ServerSavePath);

                        ViewBag.UploadStatus = allValidFiles.Count().ToString() + " files uploaded successfully.";

                        return true;
                    }
                }
            }
            catch (Exception ex)
            {
                string err = ex.ToString();
                return false;
            }
            return false;
        }

        [Authorize(Roles = "Admin, Employee")]
        // GET: charity/Delete/5
        public ActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();
            _userId = userId;

            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();
            _userRole = roles[0].Value.ToString();

            DBHelper dbh = new DBHelper();
            var model = new CharityRequestModel();

            if (User.IsInRole("Admin"))
            {
                model = dbh.GetRequests(_userId, _userRole).Find(RequestModel => RequestModel.RequestId == id);
                return View("AdminDelete", model);
            }
            else
            {
                model = dbh.GetRequests(_userId, _userRole).Find(RequestModel => RequestModel.RequestId == id);
                return View("EmployeeDelete", model);
            }
        }

        [Authorize(Roles = "Admin, Employee")]
        // POST: charity/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, CharityRequestModel Requestmodel)
        {
            DBHelper dbh = new DBHelper();

            if (User.IsInRole("Admin"))
            {
                try
                {
                    dbh.DeleteRequest(id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    string exception = "Admin Delete Error" + " " + ex.ToString();
                    ViewData["StatusDeleteError"] = "Admin Delete Error";
                    return View();
                }
            }
            else
            {
                try
                {
                    dbh.DeleteRequest(id);
                    return RedirectToAction("Index");

                }
                catch (Exception ex)
                {
                    string exception = "Employee Delete Error" + " " + ex.ToString();
                    ViewData["StatusDeleteError"] = "Employee Delete Error";
                    return View();
                }
            }
        }
    }
}

FARequest/Views/Charity/AdminDelete.cshtml
@model FARequest.Models.CharityRequestModel

@*<h3>Are you sure you want to delete this?</h3>*@
<div>
    <h4>Delete Charity Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviouslySupported)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviouslySupported)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusDesc)
        </dd>
        <dt>
            @ViewData["StatusDeleteError"]
        </dt>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FARequest/Views/Charity/AdminEdit.cshtml
@model FARequest.Models.CharityRequestModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Admin Edit Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div>
            
        </div>

        <div class="form-group">
            @Html.Label("Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @if (this.User.IsInRole("Admin"))
                {
                    @Html.DropDownListFor(model => model.StatusId, new SelectList(Model.TestStatusTypes, "Value", "Text", Model.StatusId))
                }
                else
                {
                    @Html.DropDownListFor(model => model.StatusId, new SelectList(Model.TestStatusTypes, "Value", "Text", Model.StatusId), new { @disabled = "disabled" })
                }
            </div>
        </div>

  
        @Html.HiddenFor(model => model.StatusId)

        @Html.HiddenFor(model => model.RequestId)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FARequest/Views/Charity/Create.cshtml
@model FARequest.Models.CharityRequestModel


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CharityRequestModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
        @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RequestId, "", new { @class = "text-danger" })
        </div>
    </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreviouslySupported, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PreviouslySupported)
                    @Html.ValidationMessageFor(model => model.PreviouslySupported, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount , new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocPath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocPath, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateSubmitted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateSubmitted, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateSubmitted, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FARequest/Views/Charity/CreateDocuments.cshtml
@model FARequest.Models.CharityRequestModel

@using (Html.BeginForm("CreateDocuments", "Charity", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create Charity Request</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreviouslySupported, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PreviouslySupported)
                    @Html.ValidationMessageFor(model => model.PreviouslySupported, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            <p>UPLOAD</p>
            <div class="col-md-10">
                <span>Select File:</span>
                <input type="file" name="postedFiles" multiple="multiple" />
                <hr />
                <input type="submit" value="Upload" class="btn btn-primary" />
                <br />
                <span style="color:green">@Html.Raw(ViewBag.Message)</span>
            </div>
        </div>*@

        <div>
            <table>
                <tr>
                    <td>
                         <div class="form-group">
                            <p>UPLOAD</p>
                            <div class="col-md-10">
                                <span>Select File:</span>
                                <input type="file" name="postedFiles" multiple="multiple" />
                                <hr />
                                <input type="submit" value="Upload" class="btn btn-primary" />
                                <br />
                                <span style="color:green">@Html.Raw(ViewBag.Message)</span>
                            </div>
                        </div>
                    </td>
                    <td>

                        @if (@ViewData["FileSizeError"] != null)
                        {
                            <p>
                                <h6>@ViewData["FileSizeError"]</h6>
                            </p>
                            <p>Please select a few less files and try again</p>
                        }

                        @*<ul>
                            @if (ViewData["ApprovedFileList"] != null)
                            {
                                foreach (var file in ViewData["ApprovedFileList"] as List<HttpPostedFile>)
                                {
                                    <li>
                                        @file.FileName
                                    </li>
                                }
                            }
                           
                        </ul>*@
                    </td>
                </tr>
            </table>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.UploadStatus
            </div>
        </div>  

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Requests", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FARequest/Views/Charity/Edit.cshtml
@model FARequest.Models.CharityRequestModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit Charity Request</h4>
        
        @{bool isAdmin = User.IsInRole("Admin");}
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
         @*   @Html.LabelFor(model => model.RequestId, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div id="employee" class="col-md-10">
                @Html.EditorFor(model => model.RequestId, new { htmlAttributes = new { @class = "form-control", HiddenInputAttribute = true } })
                @Html.ValidationMessageFor(model => model.RequestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="div" class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="div" class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div id="div" class="form-group">
            @Html.LabelFor(model => model.Charity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PreviouslySupported, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PreviouslySupported)
                    @Html.ValidationMessageFor(model => model.PreviouslySupported, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateSubmitted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DateSubmitted, new { @readonly = "readonly", @Class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @readonly = "readonly" ,@class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @if (this.User.IsInRole("Admin"))
                {
                    @Html.DropDownListFor(model => model.StatusId, new SelectList(Model.TestStatusTypes, "Value", "Text", Model.StatusId))
                }
                else
                {
                    @Html.DropDownListFor(model => model.StatusId, new SelectList(Model.TestStatusTypes, "Value", "Text", Model.StatusId), new { @disabled = "disabled" })
                }
            </div>
        </div>



        @if (Model.StatusId == 3)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input hidden="hidden" type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
 @Scripts.Render("~/bundles/jqueryunobtrusive") @*For unobtrusive-ajax*@
 @Scripts.Render("~/bundles/jqueryval") @*For validate and validate-unobtrusive*@




}

FARequest/Views/Charity/EmployeeDelete.cshtml
@model FARequest.Models.CharityRequestModel

<div>
    <h4>Delete Charity Request</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RequestId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviouslySupported)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviouslySupported)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocPath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocPath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateSubmitted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>
        @*<dt>
            @ViewData["StatusDeleteError"]
        </dt>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()


        @Html.HiddenFor(m => m.StatusId)

        @Html.HiddenFor(m => m.RequestId)

        if (Model.StatusId == 3)
        {
            <div class="form-actions no-color">
                <p>you cannot delete a request with approved status</p>
                <input disabled="disabled" type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
        else
        {
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                @Html.ActionLink("Back to List", "Index")
            </div>
        }


    }
</div>